// TODO: Install openai / google-generative-ai SDKs
// For now using native fetch or placeholder
import { z } from 'zod';

type LLMProvider = 'gemini' | 'openai';

interface LLMRequest {
    systemPrompt?: string;
    userPrompt: string;
    jsonSchema?: any; // Zod schema or JSON schema definition
}

export const callLLM = async (req: LLMRequest): Promise<any> => {
    const provider = (process.env.LLM_PROVIDER as LLMProvider) || 'gemini';

    if (provider === 'gemini') {
        return callGemini(req);
    } else {
        // return callOpenAI(req); // TODO
        throw new Error("OpenAI not implemented yet");
    }
};

const callGemini = async (req: LLMRequest) => {
    // Check for API Key
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === 'placeholder' || apiKey.length < 10) {
        console.log('[Mock LLM] No valid API Key found, using mock response');
        return getMockResponse(req);
    }

    try {
        console.log(`[LLM] Calling Gemini API...`);
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

        // Construct prompt content
        let promptText = req.userPrompt;
        if (req.systemPrompt) {
            promptText = `${req.systemPrompt}\n\n${req.userPrompt}`;
        }

        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: promptText }]
                }],
                generationConfig: {
                    temperature: 0.7,
                }
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error(`[LLM] API Error: ${response.status} ${response.statusText}`, errorText);
            return getMockResponse(req); // Fallback to mock on error
        }

        const data = await response.json();
        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!generatedText) {
            console.error('[LLM] No content generated', data);
            return getMockResponse(req);
        }

        // Try to parse JSON if schema was hinted or if response looks like JSON
        // For weekly plan and triage, we expect JSON.
        if (req.userPrompt.includes('JSON') || req.jsonSchema) {
            try {
                // Find JSON block in markdown
                const jsonMatch = generatedText.match(/```json\n([\s\S]*?)\n```/) || generatedText.match(/```([\s\S]*?)```/);
                const jsonStr = jsonMatch ? jsonMatch[1] : generatedText;
                return JSON.parse(jsonStr);
            } catch (e) {
                console.warn('[LLM] Failed to parse expected JSON, returning raw text or mock', e);
                // If we really needed JSON but got text, maybe fallback to mock or return raw
                return getMockResponse(req);
            }
        }

        // For summary, return text wrapped in object if needed, or just the result object expected
        if (req.userPrompt.toLowerCase().includes('summarize')) {
            return {
                summary: generatedText,
                keyPoints: ["Generated by Gemini"], // Gemini might not split this unless asked
                sentiment: "Neutral"
            };
        }

        return generatedText;

    } catch (error) {
        console.error('[LLM] Network/Logic Error:', error);
        return getMockResponse(req);
    }
};

const getMockResponse = (req: LLMRequest) => {
    console.log(`[Mock LLM] Returning mock for: ${req.userPrompt.substring(0, 50)}...`);
    // [Insert original mock logic here or similar]
    if (req.userPrompt.includes('weekly plan')) {
        return {
            weekStartDate: new Date().toISOString(),
            tasks: [
                { title: "Study Agentic Coding (Mock)", sourceType: "manual", priority: "high", status: "todo", estMins: 60 },
                { title: "Review Math Notes (Mock)", sourceType: "doc", priority: "medium", status: "todo", estMins: 45 }
            ],
            studyBlocks: [
                { title: "Deep Work Session", start: new Date().toISOString(), end: new Date(Date.now() + 3600000).toISOString() }
            ]
        };
    }

    if (req.userPrompt.includes('Triage')) {
        return [
            { id: "mock_id_1", subject: "Meeting (Mock)", from: "boss@corp.com", classification: "ACTION", extractedTasks: [], draftReply: "Sure, let's meet." }
        ];
    }

    if (req.userPrompt.toLowerCase().includes('summarize')) {
        return {
            summary: "This is a mock summary. The LLM Key might be invalid or the call failed.",
            keyPoints: ["Mock Point 1", "Mock Point 2"],
            sentiment: "Neutral"
        };
    }

    return { error: "No mock response matched" };
};
